<a href="https://colab.research.google.com/github/dnyaneshwarsirsat/EDS_360_Dnyaneshwar/blob/main/array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[11,22,33],[44,55,66],[77,88,99]])
arr1
arr2

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [ ]:
resultdiv=np.divide(arr1,arr2)
resultdiv

array([[0.09090909, 0.09090909, 0.09090909],
       [0.09090909, 0.09090909, 0.09090909],
       [0.09090909, 0.09090909, 0.09090909]])

In [ ]:
resultmulti=np.multiply(arr1,arr2)
resultmulti

array([[ 11,  44,  99],
       [176, 275, 396],
       [539, 704, 891]])

In [ ]:
resultadd=np.add(arr1,arr2)
resultadd

array([[ 12,  24,  36],
       [ 48,  60,  72],
       [ 84,  96, 108]])

In [ ]:
resultdiff=np.subtract(arr2,arr1)
resultdiff

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np. stack((a,b),axis=0)
print(c)

[[1 2 3]
 [4 5 6]]


In [ ]:
#subtraction
re_array=arr1-arr2
print("\nBy Operator Method:\n",re_array)
re_array=np.subtract(arr1,arr2)
print("By Numpy Method:\n",re_array)




By Operator Method:
 [[-10 -20 -30]
 [-40 -50 -60]
 [-70 -80 -90]]
By Numpy Method:
 [[-10 -20 -30]
 [-40 -50 -60]
 [-70 -80 -90]]


In [ ]:
#stacking
#horizantal stacking
re_array=np.hstack((arr1,arr2))
print(re_array)

#vertical staking
re_array=np.vstack((arr1,arr2))
print(re_array)

[[ 1  2  3 11 22 33]
 [ 4  5  6 44 55 66]
 [ 7  8  9 77 88 99]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 22 33]
 [44 55 66]
 [77 88 99]]
